# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend # Ruta al Dockerfile del backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Mapea el puerto 8000 del host al 8000 del contenedor
    volumes:
      # Para desarrollo en tiempo real (monta el código fuente)
      - ./backend/app:/app/app
      - ./backend/models:/app/models # Asegura que el modelo esté disponible
    environment:
      # Puedes añadir variables de entorno si tu backend las necesita
      - FASTAPI_ENV=development
    # Descomenta si usas GPU y tienes Docker con soporte NVIDIA
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

  frontend:
    build:
      context: ./frontend # Ruta al Dockerfile del frontend
      dockerfile: Dockerfile
    ports:
      # Mapea el puerto 3000 del host al puerto 80 de Nginx en el contenedor.
      # Esto hace que el frontend sea accesible desde tu red local (incluido el celular).
      - "3000:80"
    depends_on:
      - backend # Asegura que el backend intente iniciar antes que el frontend
    volumes:
      # Para desarrollo en tiempo real (monta el código fuente React)
      - ./frontend:/app
      - /app/node_modules # Previene que node_modules del host sobrescriba el del contenedor
    # environment:
      # Si necesitaras pasar variables de entorno de build a React, se harían aquí.
      # Pero con el proxy de Nginx y la URL relativa, no es estrictamente necesario para el backend.

